[package]
name = "cache-log"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
fd-lock = "4.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
